#!/bin/sh
# husky

# Created by Husky v4.2.1 (https://github.com/typicode/husky#readme)
#   At: 3/25/2020, 2:58:00 PM
#   From: /Users/viktorkirillov/Documents/GitHub/cs362/launcherreact/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
